import User from '../models/userModel.js';

//Donor registraion

export const registerDonor = async (req, res) => {
    const { email, name, role, clerkUserId } = req.body;

    try {
        const existingUser = await User.findOne({ email, role: 'donor' });

        if (existingUser) {
            return res.status(400).json({ message: 'User already exists' });
        }

        const user = new User({
            clerkUserId, // This ID is generated by Clerk during auth
            email,
            name,
            role: 'donor' 
        });

        await user.save();

        res.status(201).json({ message: 'Donor registered successfully', user });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

//Donor login (Clerk will handle authentication, so login logic is minimal)
export const loginDonor = async (req, res) => {
    const { email} = req.body;

    try {
        const user = await User.findOne({ email, role: 'donor' });

        if (!user) {
            return res.status(400).json({ message: 'Donor not found' });
        }

        // Clerk has already authenticated the user at this point.
        res.status(200).json({ message: 'Login successful', user });

    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};