import User from '../models/userModel.js';
import Donation from '../models/Donation.js';

export const registerRecipient  = async (req, res) => {
    const { email, name, role, clerkUserId } = req.body;

    try {
        const existingUser = await User.findOne({ email, role: 'recipient' });

        if (existingUser) {
            return res.status(400).json({ message: 'User already exists' });
        }

        const user = new User({
            clerkUserId, // This ID is generated by Clerk during auth
            email,
            name,
            role: 'recipient' 
        });

        await user.save();
        res.status(201).json({ message: 'Recipient registered successfully', user });
    }   catch (error) {
        res.status(500).json({ message: error.message });
    }
};

export const loginRecipient = async (req, res) => {
    const { email} = req.body;

    try {
        const user = await User.findOne({ email, role: 'recipient' });

        if (!user) {
            return res.status(400).json({ message: 'Recipient not found' });
        }

        res.status(200).json({ message: 'Login successful', user });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

export const getDashboard = async (req, res) => {
    try {
        const availableDonations = await Donation.find({ status: 'available' }).populate('donor','organization').sort({ createdAt: -1 });

        res.json({ availableDonations });

    } catch (error) {
        console.error("Error fetching available donations :", error);
        res.status(500).json({ message: 'Server error' });
    }
};